config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  root 'bookmarks#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    validates :url, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end
  
  def new
    @bookmark = Bookmark.new  #formヘルパーのデータの入れ物になる
  end
  
  def create
    @bookmark = Bookmark.new(title: params[:bookmark][:title], url: params[:bookmark][:url], name: params[:bookmark][:name])
    if @bookmark.save
        redirect_to root_path
    else
        render 'new', status: :unprocessable_entity
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.destroy # 成功時
        flash[:notice] = '削除に成功しました'
        redirect_to root_path
    else
        render 'destroy', status: :unprocessable_entity
    end
  end
  
  def show
    @bookmark = Bookmark.find(params[:id])
  end
  
  def edit
    @bookmark = Bookmark.find(params[:id])
  end
  
  def update
    bookmark = Bookmark.find(params[:id])
    bookmark.update(title: params[:bookmark][:title], url: params[:bookmark][:url], name: params[:bookmark][:name])
    redirect_to root_path

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark) do |f| %>
  <% if bookmark.errors.present? %>
    <div id="error_explanation">
      <h3>エラーがあります。</h3>
      <ul>
        <% bookmark.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :url, "URL" %><br>
    <%= f.text_field :url %>
  </div>

  <div>
    <%= f.label :name, "著者名" %><br>
    <%= f.text_field :name %>
  </div>

  <div style="margin-top: 10px;">
    <%= f.submit bookmark.persisted? ? "更新" : "登録", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>編集</h1>

<%= render "form", bookmark: @bookmark %>

<%= link_to 'Back', 'root_path' %>

app/views/bookmarks/index.html.erb
<h1>ブックマーク一覧</h1>
<table class="bookmarks-table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>URL</th>
      <th>著者名</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%=bookmark.url %></td>
        <td><%= bookmark.name %></td>
        <td class="actions">
          <%= link_to '表示', bookmark_path(bookmark), class: "btn btn-show" %>
          <%= link_to '編集', edit_bookmark_path(bookmark), class: "btn btn-edit" %>
          <%= link_to '削除', bookmark_path(bookmark), data: { turbo_method: :delete, confirm: "本当に削除しますか？" }, class: "btn btn-delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>新規追加</h1>

<%= render "form", bookmark: @bookmark %>

<%= link_to 'Back', 'root_path' %>

app/views/bookmarks/show.html.erb
<h1>詳細</h1>
<p>
  <strong>タイトル：</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>URL：</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>著者名：</strong>
  <%= @bookmark.name %>
</p>
<%= link_to 'Back', 'root_path' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ブックマークアプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <header>
      <h1>ブックマークアプリ</h1>
    </header>

    <div class="container">
      <div class="sidebar">
        <h3>メニュー</h3>
        <ul>
          <li><%= link_to "一覧", bookmarks_path %></li>
          <li><%= link_to "新規追加", new_bookmark_path %></li>
        </ul>
      </div>

      <div class="main">
        <%= yield %>
      </div>
    </div>

    <footer>
      <p>&copy; 2025 花岡 宏樹</p>
    </footer>
  </body>
</html>